trigger:
  - master

pool:
  name: 'Default'

variables:
  - name: system.debug
    value: true
  - name: BuildConfiguration
    value: 'Release'
  - name: AzureSubscription
    value: 'my-svc'
  - name: WebAppName
    value: 'your-app-service-name'
  - name: ArtifactName
    value: 'drop'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: $(ArtifactName)
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(AzureSubscription)
      appName: $(WebAppName)
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
